import { getActiveRulesByEvent, getCrmAutomationExecution, logCrmAutomationExecution } from "@/models/crm/intelligence";
import { createTask } from "@/models/tasks/writes";
import { createCrmActivity } from "@/models/crm/activities";
import { updateCrmLead } from "@/models/crm/leads";
import { updateCrmOpportunity } from "@/models/crm/opportunities";
import { getWeekNumber } from "@/lib/constants";

/**
 * Evaluates a set of conditions against a context object.
 * Returns true if ALL conditions match (AND logic).
 */
export function evaluateConditions(conditions, context) {
  if (!conditions || conditions.length === 0) return true;

  for (const cond of conditions) {
    const { field, operator, value } = cond;
    const actual = context[field];

    switch (operator) {
      case "equals":
        if (actual != value) return false;
        break;
      case "not_equals":
        if (actual == value) return false;
        break;
      case "greater_than":
        if (Number(actual) <= Number(value)) return false;
        break;
      case "less_than":
        if (Number(actual) >= Number(value)) return false;
        break;
      case "greater_than_or_equal":
        if (Number(actual) < Number(value)) return false;
        break;
      case "contains":
        if (typeof actual !== 'string' || !actual.toLowerCase().includes(String(value).toLowerCase())) return false;
        break;
      case "is_empty":
        if (actual !== null && actual !== undefined && actual !== "") return false;
        break;
      case "is_not_empty":
        if (actual === null || actual === undefined || actual === "") return false;
        break;
      default:
        // Unknown operator, fail safe
        return false;
    }
  }

  return true;
}

/**
 * Execute a single CRM automation action.
 */
async function executeAction(action, context, rule, session) {
  const { type, payload } = action;
  
  if (type === "create_task") {
    const now = new Date();
    await createTask({
      user_id: session?.user?.cid || "system",
      user_name: session?.user?.name || "System Automation",
      title: payload.title,
      description: payload.description || `Generated by rule: ${rule.name}`,
      status: "pending",
      project_id: null,
      category: "crm",
      created_week: getWeekNumber(now),
      created_year: now.getFullYear(),
      end_date: null,
      assigned_to: context.owner_cid || session?.user?.cid, // Fallback
      priority: payload.priority || "medium",
      context_type: rule.entity_type === 'lead' ? 'crm_lead' : 'crm_opportunity',
      context_id: context.id,
    });
    return { action: "create_task", success: true };
  }
  
  if (type === "add_timeline_event") {
    await createCrmActivity({
      type: "note",
      title: payload.title,
      description: payload.description || `Generated by rule: ${rule.name}`,
      outcome: "completed",
      activity_date: new Date().toISOString(),
      lead_id: rule.entity_type === 'lead' ? context.id : null,
      opportunity_id: rule.entity_type === 'opportunity' ? context.id : null,
      created_by: session?.user?.cid || "system",
    });
    return { action: "add_timeline_event", success: true };
  }

  if (type === "update_field") {
    // Dangerous, restrict heavily
    const safePayload = {};
    if (payload.status) safePayload.status = payload.status;
    if (payload.owner_cid) safePayload.owner_cid = payload.owner_cid;

    if (Object.keys(safePayload).length > 0) {
      if (rule.entity_type === 'lead') {
        await updateCrmLead(context.id, safePayload);
      } else if (rule.entity_type === 'opportunity') {
        await updateCrmOpportunity(context.id, safePayload);
      }
    }
    return { action: "update_field", fields: Object.keys(safePayload), success: true };
  }

  throw new Error(`Unknown action type: ${type}`);
}

/**
 * Fire a CRM event.
 * context must include:
 * - id: the entity ID
 * - entity_type: 'lead' or 'opportunity'
 * - <other fields for condition evaluation>
 */
export async function fireCrmEvent(eventName, context, eventId, session) {
  const result = await getActiveRulesByEvent(eventName);
  const rules = result.rows || [];

  for (const rule of rules) {
    if (rule.entity_type !== context.entity_type) continue;

    // Idempotency: an event+entity this rule already processed successfully
    // is never executed twice (retries, duplicated deliveries).
    const existing = await getCrmAutomationExecution({
      ruleId: rule.id,
      eventId,
      entityId: context.id,
    });
    if (existing && existing.status === "success") continue;

    let finalStatus = 'skipped';
    let errorMsg = null;
    let finalResult = null;
    let actionsToRun = [];
    
    try {
      const isMatch = evaluateConditions(rule.conditions, context);
      
      if (isMatch) {
        // Execute actions
        for (const action of rule.actions) {
          const res = await executeAction(action, context, rule, session);
          actionsToRun.push(res);
        }
        finalStatus = 'success';
        finalResult = { actions: actionsToRun };
      }
    } catch (err) {
      finalStatus = 'failed';
      errorMsg = err.message;
    }

    // The log row doubles as the idempotency record: ON CONFLICT updates the
    // most recent attempt's outcome; the guard above stops replays of events
    // that already succeeded.
    await logCrmAutomationExecution({
      ruleId: rule.id,
      eventId: eventId,
      entityType: rule.entity_type,
      entityId: context.id,
      status: finalStatus,
      error: errorMsg,
      result: finalResult
    });
  }
}
