-- =============================================================================
-- READ-ONLY AUDIT — which of the tables branch G needs does THIS database have?
-- =============================================================================
-- The list is every table migrations/venture_schema_align_supabase_paste.sql
-- creates, plus the two it creates via EXECUTE (journey stages, facilitator
-- playbook). Run it against both databases and diff the two outputs: that diff
-- is the real work B1 has to do.
--
--   node scripts/db-audit/run-readonly.mjs migrations/audit_production_table_inventory.sql .env.local
--   node scripts/db-audit/run-readonly.mjs migrations/audit_production_table_inventory.sql .env.audit-staging
-- =============================================================================
SELECT t.n AS table_name, to_regclass('public.' || t.n) IS NOT NULL AS exists FROM (VALUES ('venture_coaches'), ('venture_coach_assignments'), ('venture_coach_availability'), ('venture_coach_activity'), ('venture_tasks'), ('venture_task_comments'), ('venture_task_attachments'), ('venture_task_activity'), ('venture_sessions'), ('venture_session_notes'), ('venture_session_attendance'), ('venture_session_action_items'), ('venture_session_activity'), ('venture_verifications'), ('venture_verification_items'), ('venture_verification_documents'), ('venture_verification_history'), ('venture_verification_reviews'), ('venture_verification_comments'), ('venture_audit_logs'), ('venture_security_events'), ('venture_trusted_devices'), ('venture_login_history'), ('venture_failed_logins'), ('integration_providers'), ('integration_configs'), ('api_keys'), ('webhooks'), ('webhook_delivery_logs'), ('api_usage_logs'), ('system_health_checks'), ('system_metrics'), ('system_alerts'), ('system_reports'), ('job_history'), ('queue_statistics'), ('venture_origins'), ('venture_option_values'), ('platform_form_run_invitations'), ('venture_playbook_templates'), ('venture_playbook_template_stages'), ('venture_milestone_templates'), ('venture_task_templates'), ('venture_playbook_stage_milestones'), ('venture_playbook_instances'), ('venture_playbook_instance_stages'), ('venture_task_reviews'), ('venture_task_submissions'), ('venture_responsibilities'), ('venture_scope_types'), ('venture_permission_matrix'), ('venture_staff_assignments'), ('venture_notes'), ('venture_operating_plans'), ('venture_plan_sections'), ('venture_plan_links'), ('venture_plan_templates'), ('venture_plan_template_sections'), ('venture_journey_templates'), ('venture_journey_template_stages'), ('venture_journey_template_milestones'), ('venture_journey_template_tasks'), ('venture_reports'), ('venture_journey_stages'), ('venture_facilitator_playbook'), ('context_role_profiles'), ('context_applied_grants'), ('responsibility_capability_grants'), ('contact_duplicate_flags'), ('contact_group_members'), ('v2_submission_versions')) AS t(n) ORDER BY 2, 1;

-- The count, so the two databases can be compared at a glance.
SELECT count(*) AS tables_needed, count(*) FILTER (WHERE to_regclass('public.' || t.n) IS NOT NULL) AS present, count(*) FILTER (WHERE to_regclass('public.' || t.n) IS NULL) AS missing FROM (VALUES ('venture_coaches'), ('venture_coach_assignments'), ('venture_coach_availability'), ('venture_coach_activity'), ('venture_tasks'), ('venture_task_comments'), ('venture_task_attachments'), ('venture_task_activity'), ('venture_sessions'), ('venture_session_notes'), ('venture_session_attendance'), ('venture_session_action_items'), ('venture_session_activity'), ('venture_verifications'), ('venture_verification_items'), ('venture_verification_documents'), ('venture_verification_history'), ('venture_verification_reviews'), ('venture_verification_comments'), ('venture_audit_logs'), ('venture_security_events'), ('venture_trusted_devices'), ('venture_login_history'), ('venture_failed_logins'), ('integration_providers'), ('integration_configs'), ('api_keys'), ('webhooks'), ('webhook_delivery_logs'), ('api_usage_logs'), ('system_health_checks'), ('system_metrics'), ('system_alerts'), ('system_reports'), ('job_history'), ('queue_statistics'), ('venture_origins'), ('venture_option_values'), ('platform_form_run_invitations'), ('venture_playbook_templates'), ('venture_playbook_template_stages'), ('venture_milestone_templates'), ('venture_task_templates'), ('venture_playbook_stage_milestones'), ('venture_playbook_instances'), ('venture_playbook_instance_stages'), ('venture_task_reviews'), ('venture_task_submissions'), ('venture_responsibilities'), ('venture_scope_types'), ('venture_permission_matrix'), ('venture_staff_assignments'), ('venture_notes'), ('venture_operating_plans'), ('venture_plan_sections'), ('venture_plan_links'), ('venture_plan_templates'), ('venture_plan_template_sections'), ('venture_journey_templates'), ('venture_journey_template_stages'), ('venture_journey_template_milestones'), ('venture_journey_template_tasks'), ('venture_reports'), ('venture_journey_stages'), ('venture_facilitator_playbook'), ('context_role_profiles'), ('context_applied_grants'), ('responsibility_capability_grants'), ('contact_duplicate_flags'), ('contact_group_members'), ('v2_submission_versions')) AS t(n);
