import { initDb } from "@/lib/db";
import { NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import {
  getProjectReportTaskStats,
  getRecentTasksForReport,
  findProjectUpdateForReport,
  updateAutoGeneratedProjectUpdate,
  createAutoGeneratedProjectUpdate,
} from "@/models/projects";

function getWeekNumber(date) {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  return Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
}

export async function POST(req, { params }) {
  try {
    await initDb();
    const authError = await requireAuth(["super_admin", "staff", "program_manager"]);
    if (authError) return authError;
    const { id } = await params;

    const now = new Date();
    const w = getWeekNumber(now);
    const y = now.getFullYear();

    const taskStats = await getProjectReportTaskStats(id);
    const ts = taskStats.rows[0] || {};
    const total = parseInt(ts.t) || 0;
    const completed = parseInt(ts.c) || 0;
    const progress = total > 0 ? Math.round((completed / total) * 100) : 0;
    const activeBlockers = parseInt(ts.b) || 0;

    const recent = await getRecentTasksForReport(id);

    const summary = `Week ${w}, ${y} — ${progress}% complete (${completed}/${total}) | ${ts.ip || 0} active | ${activeBlockers} blocked | ${ts.co || 0} carry-over`;
    const details = recent.rows.map(t => `• ${t.title} (${t.status})`).join("\n");

    const overall = activeBlockers > 0 ? "blocked" : (ts.co || 0) > (total * 0.3) ? "at_risk" : "on_track";

    const exist = await findProjectUpdateForReport(id, w, y);

    if (exist.rows.length > 0) {
      await updateAutoGeneratedProjectUpdate(
        summary,
        details,
        overall,
        exist.rows[0].id,
      );
    } else {
      await createAutoGeneratedProjectUpdate(id, w, y, summary, details, overall);
    }

    return NextResponse.json({ success: true, week: w, year: y, progress, summary });
  } catch (e) {
    return NextResponse.json({ success: false, error: e.message }, { status: 500 });
  }
}
