import { initDb } from "@/lib/db";
import { NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import {
  getProjectReportTaskStats,
  getRecentTasksForReport,
  findProjectUpdateForReport,
  updateAutoGeneratedProjectUpdate,
  createAutoGeneratedProjectUpdate,
} from "@/models/projects";

function getWeekNumber(date) {
  const utcDate = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = utcDate.getUTCDay() || 7;
  utcDate.setUTCDate(utcDate.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(utcDate.getUTCFullYear(), 0, 1));
  return Math.ceil(((utcDate - yearStart) / 86400000 + 1) / 7);
}

export async function POST(req, { params }) {
  try {
    await initDb();
    const authError = await requireAuth(["super_admin", "staff", "program_manager"]);
    if (authError) return authError;
    const { id } = await params;

    const now = new Date();
    const weekNumber = getWeekNumber(now);
    const year = now.getFullYear();

    const taskStats = await getProjectReportTaskStats(id);
    const taskStatsRow = taskStats.rows[0] || {};
    const total = parseInt(taskStatsRow.t) || 0;
    const completed = parseInt(taskStatsRow.c) || 0;
    const progress = total > 0 ? Math.round((completed / total) * 100) : 0;
    const activeBlockers = parseInt(taskStatsRow.b) || 0;

    const recent = await getRecentTasksForReport(id);

    const summary = `Week ${weekNumber}, ${year} — ${progress}% complete (${completed}/${total}) | ${taskStatsRow.ip || 0} active | ${activeBlockers} blocked | ${taskStatsRow.co || 0} carry-over`;
    const details = recent.rows.map((task) => `• ${task.title} (${task.status})`).join("\n");

    const overall = activeBlockers > 0 ? "blocked" : (taskStatsRow.co || 0) > (total * 0.3) ? "at_risk" : "on_track";

    const existingUpdate = await findProjectUpdateForReport(id, weekNumber, year);

    if (existingUpdate.rows.length > 0) {
      await updateAutoGeneratedProjectUpdate(
        summary,
        details,
        overall,
        existingUpdate.rows[0].id,
      );
    } else {
      await createAutoGeneratedProjectUpdate(id, weekNumber, year, summary, details, overall);
    }

    return NextResponse.json({ success: true, week: weekNumber, year, progress, summary });
  } catch (error) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
