/**
 * Behaviour of the admin project services (service layer).
 *
 * The repository is mocked: the batched list aggregation, the detail assembly,
 * the weekly-update upsert, the approval workflow (including its object-level
 * check and its tolerant read) and the generated-report derivation.
 */

jest.mock("@/models/projects", () => ({
  getAdminProjects: jest.fn(),
  getAdminTaskStatsByProjectIds: jest.fn(),
  countDatedTasksByProjectIds: jest.fn(),
  getAdminBlockerStatsByProjectIds: jest.fn(),
  getAdminProjectDetails: jest.fn(),
  getTaskStatsForProject: jest.fn(),
  getTasksForProject: jest.fn(),
  getResourcesByTaskIds: jest.fn(),
  getBlockersByTaskIds: jest.fn(),
  getSubtasksByParentTaskIds: jest.fn(),
  getProjectBlockers: jest.fn(),
  getProjectMembersUnion: jest.fn(),
  getProjectTimeline: jest.fn(),
  countDatedTasksForProject: jest.fn(),
  getProjectUpdates: jest.fn(),
  findProjectUpdateId: jest.fn(),
  updateProjectUpdate: jest.fn(),
  createProjectUpdate: jest.fn(),
  getProjectApprovalRequests: jest.fn(),
  getProjectApprovalRequestById: jest.fn(),
  updateProjectApprovalRequestStatus: jest.fn(),
  linkTaskToProject: jest.fn(),
  createApprovalApprovedNotification: jest.fn(),
  createApprovalRejectedNotification: jest.fn(),
  getProjectReportTaskStats: jest.fn(),
  getRecentTasksForReport: jest.fn(),
  findProjectUpdateForReport: jest.fn(),
  updateAutoGeneratedProjectUpdate: jest.fn(),
  createAutoGeneratedProjectUpdate: jest.fn(),
}));

jest.mock("@/lib/db/queries/tasks", () => ({
  getTaskTitleById: jest.fn(async () => "Task"),
}));

const models = require("@/models/projects");
const { listProjects, getProjectDetail } = require("@/services/dashboard/adminProjects");
const { listProjectUpdates, saveProjectUpdate } = require("@/services/dashboard/adminProjectUpdates");
const { listApprovals, reviewApproval } = require("@/services/dashboard/adminProjectApprovals");
const { generateProjectReport } = require("@/services/dashboard/adminProjectReports");

beforeEach(() => {
  jest.clearAllMocks();
  models.getAdminProjects.mockResolvedValue({ rows: [] });
  models.getAdminTaskStatsByProjectIds.mockResolvedValue({ rows: [] });
  models.countDatedTasksByProjectIds.mockResolvedValue({ rows: [] });
  models.getAdminBlockerStatsByProjectIds.mockResolvedValue({ rows: [] });
  models.getProjectUpdates.mockResolvedValue({ rows: [] });
  models.findProjectUpdateId.mockResolvedValue({ rows: [] });
  models.createProjectUpdate.mockResolvedValue({ rows: [{ id: 77 }] });
  models.updateProjectUpdate.mockResolvedValue({});
  models.getProjectApprovalRequests.mockResolvedValue({ rows: [] });
  models.getProjectReportTaskStats.mockResolvedValue({ rows: [] });
  models.getRecentTasksForReport.mockResolvedValue({ rows: [] });
  models.findProjectUpdateForReport.mockResolvedValue({ rows: [] });
  models.createAutoGeneratedProjectUpdate.mockResolvedValue({});
  models.updateAutoGeneratedProjectUpdate.mockResolvedValue({});
});

describe("listProjects", () => {
  test("enriches each project with rates and aggregates the totals", async () => {
    models.getAdminProjects.mockResolvedValue({ rows: [{ id: 1, name: "P" }] });
    models.getAdminTaskStatsByProjectIds.mockResolvedValue({
      rows: [
        {
          pid: "1",
          total: 4,
          completed: 2,
          in_progress: 1,
          blocked: 0,
          carried_over: 1,
          pending: 0,
          dated: 3,
        },
      ],
    });
    models.getAdminBlockerStatsByProjectIds.mockResolvedValue({
      rows: [{ pid: "1", total: 2, active: 1 }],
    });

    const { body } = await listProjects({ includeArchived: null, programId: null });
    const project = body.projects[0];
    expect(project.completionRate).toBe(50);
    expect(project.timelineHealth).toBe(75);
    expect(project.taskStats.total).toBe(4);
    expect(project.blockerStats.active).toBe(1);
    expect(body.totals).toEqual({
      totalTasks: 4,
      completedTasks: 2,
      totalBlockers: 2,
      activeBlockers: 1,
    });
  });

  test("no projects runs no batched aggregation", async () => {
    const { body } = await listProjects({ includeArchived: null, programId: null });
    expect(body.projects).toEqual([]);
    expect(models.getAdminTaskStatsByProjectIds).not.toHaveBeenCalled();
  });
});

describe("getProjectDetail", () => {
  test("an unknown project is a 404", async () => {
    models.getAdminProjectDetails.mockResolvedValue({ rows: [] });
    const result = await getProjectDetail(9);
    expect(result.status).toBe(404);
  });

  test("attaches blockers, subtasks and resources and derives the rates", async () => {
    models.getAdminProjectDetails.mockResolvedValue({ rows: [{ id: 9, name: "P" }] });
    models.getTaskStatsForProject.mockResolvedValue({
      rows: [{ total: 4, completed: 2, in_progress: 1, blocked: 0, carried_over: 1, pending: 0 }],
    });
    models.getTasksForProject.mockResolvedValue({ rows: [{ id: 11 }, { id: 12 }] });
    models.getResourcesByTaskIds.mockResolvedValue({
      rows: [
        { task_id: 11, id: "r1", name: "Doc", url: "u", type: "file", file_name: "f", file_size: 10, uploaded_by: "U" },
      ],
    });
    models.getBlockersByTaskIds.mockResolvedValue({
      rows: [{ task_id: 11, id: "b1", title: "B" }],
    });
    models.getSubtasksByParentTaskIds.mockResolvedValue({
      rows: [{ task_id: 11, id: "s1" }],
    });
    models.getProjectBlockers.mockResolvedValue({ rows: [{ id: "pb1" }] });
    models.getProjectMembersUnion.mockResolvedValue({ rows: [{ cid: "U1" }] });
    models.getProjectTimeline.mockResolvedValue({ rows: [{ id: "t1" }] });
    models.countDatedTasksForProject.mockResolvedValue({ rows: [{ count: 3 }] });

    const { body } = await getProjectDetail(9);
    const project = body.project;
    expect(project.completionRate).toBe(50);
    expect(project.timelineHealth).toBe(75);
    expect(project.tasks[0].blockers).toHaveLength(1);
    expect(project.tasks[0].subtasks).toHaveLength(1);
    expect(project.tasks[0].resources).toHaveLength(1);
    expect(project.members).toHaveLength(1);
    expect(project.timeline).toHaveLength(1);
  });
});

describe("saveProjectUpdate", () => {
  test("a missing user_id is a 400 and writes nothing", async () => {
    const result = await saveProjectUpdate({ projectId: 9, payload: {} });
    expect(result.status).toBe(400);
    expect(models.createProjectUpdate).not.toHaveBeenCalled();
  });

  test("no existing row creates one", async () => {
    const result = await saveProjectUpdate({
      projectId: 9,
      payload: { user_id: "U1", user_name: "Ann", accomplishments: "Did things" },
    });
    expect(models.createProjectUpdate).toHaveBeenCalled();
    expect(result.body).toMatchObject({ success: true, id: 77, action: "created" });
    expect(result.body.week_number).toBeGreaterThan(0);
    expect(result.body.year).toBeGreaterThan(2000);
  });

  test("an existing row is updated with only the provided fields", async () => {
    models.findProjectUpdateId.mockResolvedValue({ rows: [{ id: 5 }] });
    const result = await saveProjectUpdate({
      projectId: 9,
      payload: { user_id: "U1", week_number: 10, year: 2026, notes: "n", status: "draft" },
    });
    expect(models.createProjectUpdate).not.toHaveBeenCalled();
    const [fields, args] = models.updateProjectUpdate.mock.calls[0];
    expect(fields).toEqual([
      "notes = ?",
      "status = ?",
      "updated_at = CURRENT_TIMESTAMP",
    ]);
    expect(args).toEqual(["n", "draft", 5]);
    expect(result.body.action).toBe("updated");
  });

  test("an existing row with nothing to change writes nothing", async () => {
    models.findProjectUpdateId.mockResolvedValue({ rows: [{ id: 5 }] });
    await saveProjectUpdate({
      projectId: 9,
      payload: { user_id: "U1", week_number: 10, year: 2026 },
    });
    expect(models.updateProjectUpdate).not.toHaveBeenCalled();
  });
});

describe("listApprovals", () => {
  test("returns the rows", async () => {
    models.getProjectApprovalRequests.mockResolvedValue({ rows: [{ id: 1 }] });
    const result = await listApprovals(9);
    expect(result.body.requests).toEqual([{ id: 1 }]);
  });

  test("a failing query answers an empty list instead of failing", async () => {
    models.getProjectApprovalRequests.mockRejectedValue(new Error("no table"));
    const result = await listApprovals(9);
    expect(result.status).toBe(200);
    expect(result.body).toEqual({ success: true, requests: [] });
  });
});

describe("reviewApproval", () => {
  const base = {
    projectId: "9",
    requestId: 3,
    reviewerId: "R1",
    reviewerName: "Reviewer",
    action: "approved",
    rejectionReason: undefined,
  };

  test("missing fields are a 400", async () => {
    const result = await reviewApproval({ ...base, requestId: null });
    expect(result.status).toBe(400);
  });

  test("an unknown action is a 400", async () => {
    const result = await reviewApproval({ ...base, action: "maybe" });
    expect(result.status).toBe(400);
  });

  test("rejecting without a reason is a 400", async () => {
    const result = await reviewApproval({ ...base, action: "rejected" });
    expect(result.status).toBe(400);
  });

  test("an unknown request is a 404", async () => {
    models.getProjectApprovalRequestById.mockResolvedValue({ rows: [] });
    const result = await reviewApproval(base);
    expect(result.status).toBe(404);
  });

  test("a request belonging to another project is a 404 (object-level check)", async () => {
    models.getProjectApprovalRequestById.mockResolvedValue({
      rows: [{ id: 3, project_id: "OTHER", task_id: "T1" }],
    });
    const result = await reviewApproval(base);
    expect(result.status).toBe(404);
    expect(models.updateProjectApprovalRequestStatus).not.toHaveBeenCalled();
  });

  test("approving links the task and notifies the requester", async () => {
    models.getProjectApprovalRequestById.mockResolvedValue({
      rows: [{ id: 3, project_id: "9", task_id: "T1", requester_id: "REQ" }],
    });
    const result = await reviewApproval(base);
    expect(models.updateProjectApprovalRequestStatus).toHaveBeenCalledWith(
      "approved",
      "R1",
      undefined,
      3,
    );
    expect(models.linkTaskToProject).toHaveBeenCalledWith("9", "T1");
    expect(models.createApprovalApprovedNotification).toHaveBeenCalled();
    expect(result.body.message).toContain("approved");
  });

  test("rejecting notifies the requester with the reason", async () => {
    models.getProjectApprovalRequestById.mockResolvedValue({
      rows: [{ id: 3, project_id: "9", task_id: "T1", requester_id: "REQ" }],
    });
    await reviewApproval({
      ...base,
      action: "rejected",
      rejectionReason: "not relevant",
    });
    expect(models.linkTaskToProject).not.toHaveBeenCalled();
    const [, , message] = models.createApprovalRejectedNotification.mock.calls[0];
    expect(message).toContain("not relevant");
  });

  test("an unavailable workflow answers a 200 with success false", async () => {
    models.getProjectApprovalRequestById.mockResolvedValue({
      rows: [{ id: 3, project_id: "9", task_id: "T1", requester_id: "REQ" }],
    });
    models.updateProjectApprovalRequestStatus.mockRejectedValue(new Error("no table"));
    const result = await reviewApproval(base);
    expect(result.status).toBe(200);
    expect(result.body.success).toBe(false);
  });
});

describe("generateProjectReport", () => {
  test("derives on_track, at_risk or blocked from the stats", async () => {
    models.getProjectReportTaskStats.mockResolvedValue({
      rows: [{ t: 10, c: 5, ip: 2, b: 0, co: 1 }],
    });
    await generateProjectReport(9);
    expect(models.createAutoGeneratedProjectUpdate).toHaveBeenLastCalledWith(
      9,
      expect.any(Number),
      expect.any(Number),
      expect.any(String),
      expect.any(String),
      "on_track",
    );

    models.getProjectReportTaskStats.mockResolvedValue({
      rows: [{ t: 10, c: 5, ip: 2, b: 0, co: 5 }],
    });
    await generateProjectReport(9);
    expect(models.createAutoGeneratedProjectUpdate).toHaveBeenLastCalledWith(
      9,
      expect.any(Number),
      expect.any(Number),
      expect.any(String),
      expect.any(String),
      "at_risk",
    );

    models.getProjectReportTaskStats.mockResolvedValue({
      rows: [{ t: 10, c: 5, ip: 2, b: 3, co: 0 }],
    });
    await generateProjectReport(9);
    expect(models.createAutoGeneratedProjectUpdate).toHaveBeenLastCalledWith(
      9,
      expect.any(Number),
      expect.any(Number),
      expect.any(String),
      expect.any(String),
      "blocked",
    );
  });

  test("an existing row for the week is updated in place", async () => {
    models.getProjectReportTaskStats.mockResolvedValue({
      rows: [{ t: 10, c: 5, ip: 2, b: 0, co: 0 }],
    });
    models.findProjectUpdateForReport.mockResolvedValue({ rows: [{ id: 9 }] });
    await generateProjectReport(9);
    expect(models.createAutoGeneratedProjectUpdate).not.toHaveBeenCalled();
    expect(models.updateAutoGeneratedProjectUpdate).toHaveBeenCalledWith(
      expect.any(String),
      expect.any(String),
      "on_track",
      9,
    );
  });
});
