/**
 * SECURITY — Lot 9 (scope on the remaining admin/staffing surfaces).
 *
 * Registry findings:
 *   - AUTHZ-ADM-4: `programs` PUT let any staff edit ANY program; `facilitators/
 *     invite-bulk` let a `program_manager` bulk-invite facilitators into a
 *     program they were not staffed on; `admin/projects/[id]/reports/generate`
 *     wrote a weekly report onto any project id.
 *
 * The tests drive the real handlers and prove the scope is enforced, that the
 * missing `program_manager` check is now present, and that Super Admin (or a
 * project member) still works.
 */

jest.mock("@/lib/db", () => ({
  __esModule: true,
  default: { execute: jest.fn(async () => ({ rows: [] })) },
  initDb: jest.fn(async () => true),
}));

jest.mock("@/lib/auth", () => ({
  requireAuth: jest.fn(async () => null),
  getSession: jest.fn(async () => ({ cid: "USR_STAFF", role: "staff", email: "s@x.test" })),
  hasProgramManagementAccess: jest.fn(() => false),
  requireAssignmentAccess: jest.fn(async () => null),
  assertNoParticipantFacilitatorConflict: jest.fn(async () => null),
  isAssignedPmForProgram: jest.fn(async () => true),
  requireProjectAccess: jest.fn(async () => null),
}));

jest.mock("@/lib/authorization", () => ({
  getAuthorizationContext: jest.fn(async () => ({ isSuperAdmin: false })),
  requireAuthorization: jest.fn(async () => null),
  authorize: jest.fn(() => false),
}));

jest.mock("@/lib/authorization/scope", () => ({
  isWithinScope: jest.fn(async () => true),
}));

jest.mock("@/lib/email", () => ({
  sendInviteEmail: jest.fn(async () => true),
  sendLoginEmail: jest.fn(async () => true),
}));

jest.mock("@/lib/token-hashing", () => ({
  hashToken: jest.fn((token) => `hash-${token}`),
  ensureTokenHashColumns: jest.fn(async () => true),
}));

jest.mock("@/lib/facilitator-permissions", () => ({
  buildFullFacilitatorPermissions: jest.fn(() => ({ all: true })),
  parsePermissions: jest.fn(() => ({})),
}));

jest.mock("@/models/programs", () => ({
  addParticipantProgramMembership: jest.fn(async () => ({})),
  assignFamilyToProgram: jest.fn(async () => ({})),
  createV2Program: jest.fn(async () => ({})),
  ensureSystemFacilitatorsGroup: jest.fn(async () => ({})),
  getAllPrograms: jest.fn(async () => ({ rows: [] })),
  getContactsByFamilyName: jest.fn(async () => ({ rows: [] })),
  getFamilyNameById: jest.fn(async () => ({ rows: [] })),
  getProgramExists: jest.fn(async () => ({ rows: [{ id: "P1" }] })),
  unassignAllFamilies: jest.fn(async () => ({})),
  unassignFamiliesNotInList: jest.fn(async () => ({})),
  updateProgramFields: jest.fn(async () => ({})),
}));

jest.mock("@/models/facilitation", () => ({
  addFacilitatorAssignedTimelineEvent: jest.fn(async () => ({})),
  addFacilitatorContactRole: jest.fn(async () => ({})),
  addFacilitatorInvitedTimelineEvent: jest.fn(async () => ({})),
  createFacilitatorContact: jest.fn(async () => ({})),
  createFacilitatorInviteToken: jest.fn(async () => ({})),
  fillContactProgramLink: jest.fn(async () => ({})),
  findContactByEmailForInvite: jest.fn(async () => ({ rows: [] })),
  findParticipantConflictForFacilitatorInvite: jest.fn(async () => ({ rows: [] })),
  getProgramForFacilitatorInvite: jest.fn(async () => ({ rows: [{ name: "Program" }] })),
  invalidatePasswordSetupTokens: jest.fn(async () => ({})),
  isAlreadyFacilitatorInProgram: jest.fn(async () => ({ rows: [] })),
  upsertFacilitatorProgramStaff: jest.fn(async () => ({})),
}));

jest.mock("@/models/projects", () => ({
  getProjectReportTaskStats: jest.fn(async () => ({ rows: [{ t: 0, c: 0 }] })),
  getRecentTasksForReport: jest.fn(async () => ({ rows: [] })),
  findProjectUpdateForReport: jest.fn(async () => ({ rows: [] })),
  updateAutoGeneratedProjectUpdate: jest.fn(async () => ({})),
  createAutoGeneratedProjectUpdate: jest.fn(async () => ({})),
}));

const { isWithinScope } = require("@/lib/authorization/scope");
const { getAuthorizationContext } = require("@/lib/authorization");
const { getSession, requireProjectAccess, isAssignedPmForProgram } = require("@/lib/auth");
const programsModel = require("@/models/programs");
const facilitationModel = require("@/models/facilitation");
const projectsModel = require("@/models/projects");

const programs = require("@/app/api/programs/route");
const inviteBulk = require("@/app/api/facilitators/invite-bulk/route");
const reportGenerate = require("@/app/api/admin/projects/[id]/reports/generate/route");

const post = (url, body) =>
  new Request(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
const put = (url, body) =>
  new Request(url, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });

beforeEach(() => {
  jest.clearAllMocks();
  isWithinScope.mockResolvedValue(true);
  getAuthorizationContext.mockResolvedValue({ isSuperAdmin: false });
  getSession.mockResolvedValue({ cid: "USR_STAFF", role: "staff", email: "s@x.test" });
  requireProjectAccess.mockResolvedValue(null);
  isAssignedPmForProgram.mockResolvedValue(true);
});

describe("programs PUT is program-scoped", () => {
  test("editing a program you are not staffed on is refused, nothing written", async () => {
    isWithinScope.mockResolvedValueOnce(false);
    const res = await programs.PUT(put("http://localhost/api/programs", { id: "P-OTHER", name: "Renamed" }));
    const body = await res.json();

    expect(res.status).toBe(403);
    expect(body.missing).toEqual({ scope: "program_staffed", wave: "content" });
    expect(programsModel.updateProgramFields).not.toHaveBeenCalled();
  });

  test("editing a program you are staffed on still works", async () => {
    const res = await programs.PUT(put("http://localhost/api/programs", { id: "P1", name: "Renamed" }));

    expect(res.status).toBe(200);
    expect(isWithinScope).toHaveBeenCalledWith("program_staffed", "USR_STAFF", "P1", { email: "s@x.test" });
    expect(programsModel.updateProgramFields).toHaveBeenCalled();
  });

  test("Super Admin may edit any program", async () => {
    getAuthorizationContext.mockResolvedValueOnce({ isSuperAdmin: true });
    isWithinScope.mockResolvedValueOnce(false);

    const res = await programs.PUT(put("http://localhost/api/programs", { id: "P-OTHER", name: "Renamed" }));

    expect(res.status).toBe(200);
    expect(programsModel.updateProgramFields).toHaveBeenCalled();
  });
});

describe("bulk facilitator invites are program-scoped for every role", () => {
  test("a program_manager out of scope is refused (the old bypass), nothing written", async () => {
    getSession.mockResolvedValue({ cid: "USR_PM", role: "program_manager", email: "pm@x.test" });
    isWithinScope.mockResolvedValueOnce(false);

    const res = await inviteBulk.POST(post("http://localhost/api/facilitators/invite-bulk", {
      program_id: "P-OTHER", emails: ["a@x.test"],
    }));

    expect(res.status).toBe(403);
    expect(facilitationModel.upsertFacilitatorProgramStaff).not.toHaveBeenCalled();
  });

  test("a staffed staff member who is NOT the program's PM is refused", async () => {
    isAssignedPmForProgram.mockResolvedValueOnce(false);

    const res = await inviteBulk.POST(post("http://localhost/api/facilitators/invite-bulk", {
      program_id: "P1", emails: ["a@x.test"],
    }));

    expect(res.status).toBe(403);
    expect(facilitationModel.upsertFacilitatorProgramStaff).not.toHaveBeenCalled();
  });

  test("a staffed program_manager proceeds to invite", async () => {
    getSession.mockResolvedValue({ cid: "USR_PM", role: "program_manager", email: "pm@x.test" });

    const res = await inviteBulk.POST(post("http://localhost/api/facilitators/invite-bulk", {
      program_id: "P1", emails: ["a@x.test"], preview: true,
    }));

    expect(res.status).toBe(200);
    expect(isWithinScope).toHaveBeenCalledWith("program_staffed", "USR_PM", "P1", { email: "pm@x.test" });
  });
});

describe("project report generation is project-scoped", () => {
  test("writing a report onto a project you do not belong to is refused", async () => {
    requireProjectAccess.mockResolvedValueOnce(new Response(null, { status: 403 }));

    const res = await reportGenerate.POST(
      new Request("http://localhost/api/admin/projects/15/reports/generate", { method: "POST" }),
      { params: Promise.resolve({ id: "15" }) },
    );

    expect(res.status).toBe(403);
    expect(requireProjectAccess).toHaveBeenCalledWith("15");
    expect(projectsModel.createAutoGeneratedProjectUpdate).not.toHaveBeenCalled();
    expect(projectsModel.updateAutoGeneratedProjectUpdate).not.toHaveBeenCalled();
  });

  test("a project member generates the report", async () => {
    const res = await reportGenerate.POST(
      new Request("http://localhost/api/admin/projects/15/reports/generate", { method: "POST" }),
      { params: Promise.resolve({ id: "15" }) },
    );

    expect(res.status).toBe(200);
    expect(projectsModel.createAutoGeneratedProjectUpdate).toHaveBeenCalled();
  });
});
