import db from "@/lib/db";

/**
 * Projects model — auto-generated weekly reports (REPOSITORY layer).
 *
 * The report task stats, recent-task lines and the update find/overwrite/insert
 * used by the report generator, split verbatim out of `models/projects.js` —
 * see docs/LAYER_SPLIT.md.
 *
 * Model-layer rules: no HTTP, one function per query, named after the data.
 */

/**
 * Task-status stats for the auto-generated weekly report.
 * Uses native Postgres $n placeholders (no ? translation) — byte-identical
 * to the original inline query.
 */
export async function getProjectReportTaskStats(id) {
  return db.execute({
    sql: `SELECT COUNT(*) AS t, SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) AS c,
            SUM(CASE WHEN status='in_progress' THEN 1 ELSE 0 END) AS ip,
            SUM(CASE WHEN status='blocked' THEN 1 ELSE 0 END) AS b,
            SUM(CASE WHEN status='carried_over' THEN 1 ELSE 0 END) AS co
            FROM tasks WHERE project_id::text = $1`,
    args: [id],
  });
}

/** Recently updated tasks of a project (report detail lines, capped at 10). */
export async function getRecentTasksForReport(id) {
  return db.execute({
    sql: "SELECT title, status FROM tasks WHERE project_id::text = $1 ORDER BY updated_at DESC LIMIT 10",
    args: [id],
  });
}

/** Id of an existing update for the report's project/week/year. */
export async function findProjectUpdateForReport(id, weekNumber, year) {
  return db.execute({
    sql: "SELECT id FROM v2_project_updates WHERE project_id::text = $1 AND week_number = $2 AND year = $3",
    args: [id, weekNumber, year],
  });
}

/** Overwrite an existing update with the auto-generated report contents. */
export async function updateAutoGeneratedProjectUpdate(
  summary,
  details,
  overall,
  updateId,
) {
  return db.execute({
    sql: "UPDATE v2_project_updates SET accomplishments=$1, current_focus=$2, overall_status=$3, notes=$4, updated_at=NOW() WHERE id=$5",
    args: [summary, details, overall, "Auto-generated", updateId],
  });
}

/** Insert the auto-generated weekly report as a submitted update. */
export async function createAutoGeneratedProjectUpdate(
  id,
  weekNumber,
  year,
  summary,
  details,
  overall,
) {
  return db.execute({
    sql: "INSERT INTO v2_project_updates (project_id,user_id,user_name,week_number,year,status,accomplishments,current_focus,overall_status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",
    args: [
      id,
      "system",
      "System",
      weekNumber,
      year,
      "submitted",
      summary,
      details,
      overall,
      "Auto-generated",
    ],
  });
}
