/**
 * Admin project reports — the auto-generated weekly report (SERVICE layer).
 *
 * The work behind `POST /api/admin/projects/[id]/reports/generate`: the week/year
 * framing, the progress and overall-status derivation, the summary/details
 * composition and the upsert of the auto-generated update.
 *
 * HTTP-free: it reads and writes through `@/models/projects`; answers
 * `{ status, body }`. The controller keeps `initDb`, the role check, the
 * project-scope guard and the envelope.
 */

import {
  createAutoGeneratedProjectUpdate,
  findProjectUpdateForReport,
  getProjectReportTaskStats,
  getRecentTasksForReport,
  updateAutoGeneratedProjectUpdate,
} from "@/models/projects";
import { getWeekNumber } from "@/services/dashboard/weeks";

/** Compose and store the week's auto-generated narrative for a project. */
export async function generateProjectReport(projectId) {
  const now = new Date();
  const weekNumber = getWeekNumber(now);
  const year = now.getFullYear();

  const taskStats = await getProjectReportTaskStats(projectId);
  const taskStatsRow = taskStats.rows[0] || {};
  const total = parseInt(taskStatsRow.t) || 0;
  const completed = parseInt(taskStatsRow.c) || 0;
  const progress = total > 0 ? Math.round((completed / total) * 100) : 0;
  const activeBlockers = parseInt(taskStatsRow.b) || 0;

  const recent = await getRecentTasksForReport(projectId);

  const summary = `Week ${weekNumber}, ${year} — ${progress}% complete (${completed}/${total}) | ${taskStatsRow.ip || 0} active | ${activeBlockers} blocked | ${taskStatsRow.co || 0} carry-over`;
  const details = recent.rows
    .map((task) => `• ${task.title} (${task.status})`)
    .join("\n");

  const overall =
    activeBlockers > 0
      ? "blocked"
      : (taskStatsRow.co || 0) > total * 0.3
        ? "at_risk"
        : "on_track";

  const existingUpdate = await findProjectUpdateForReport(projectId, weekNumber, year);

  if (existingUpdate.rows.length > 0) {
    await updateAutoGeneratedProjectUpdate(
      summary,
      details,
      overall,
      existingUpdate.rows[0].id,
    );
  } else {
    await createAutoGeneratedProjectUpdate(
      projectId,
      weekNumber,
      year,
      summary,
      details,
      overall,
    );
  }

  return {
    status: 200,
    body: { success: true, week: weekNumber, year, progress, summary },
  };
}
